/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.BlacklistRequest
import io.swagger.client.model.BlacklistResponse
import io.swagger.client.model.Blacklisted
import io.swagger.client.model.BlacklistedList
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Add a company to the blacklist 
   * 
   * Expected answers:
   *   code 200 : BlacklistResponse (Successful response)
   * 
   * @param blacklisted 
   */
  def blacklistMockBlacklistedHtmlPost(blacklisted: Option[Blacklisted] = None): ApiRequest[BlacklistResponse] =
    ApiRequest[BlacklistResponse](ApiMethods.POST, "http://localhost:8080/ssm-master", "/blacklist/mock/blacklisted.html", "application/json")
      .withBody(blacklisted)
      .withSuccessResponse[BlacklistResponse](200)
        /**
   * Get a list of blacklisted companies 
   * 
   * Expected answers:
   *   code 200 : BlacklistedList (Successful response)
   */
  def blacklistMockListHtmlPost(): ApiRequest[BlacklistedList] =
    ApiRequest[BlacklistedList](ApiMethods.POST, "http://localhost:8080/ssm-master", "/blacklist/mock/list.html", "application/json")
      .withSuccessResponse[BlacklistedList](200)
        /**
   * Validates the company number against the blacklist 
   * 
   * Expected answers:
   *   code 200 : BlacklistResponse (Successful response)
   * 
   * @param request 
   */
  def blacklistMockValidateHtmlPost(request: Option[BlacklistRequest] = None): ApiRequest[BlacklistResponse] =
    ApiRequest[BlacklistResponse](ApiMethods.POST, "http://localhost:8080/ssm-master", "/blacklist/mock/validate.html", "application/json")
      .withBody(request)
      .withSuccessResponse[BlacklistResponse](200)
      

}

